CREATE TABLE EMP (ID int PRIMARY KEY NOT NULL, NAME varchar(50) NOT NULL);

CREATE TABLE ADDR (ID int NOT NULL,ADDRESS varchar(50) NOT NULL);
ALTER TABLE ADDR ADD CONSTRAINT ADDR_ID_REF FOREIGN KEY (ID) REFERENCES EMP(ID);